FROM postgres
EXPOSE 5432
# ENV DB_NAME presslydb
# ENV DB_USER admin
# ENV DB_PASS password
# ADD setup-database.sh /docker-entrypoint-initdb.d/setup-database.sh
# RUN chmod 755 /docker-entrypoint-initdb.d/setup-database.sh