web:
  build: .
  ports:
    - "80:3000"
  environment:
    POSTGRES_HOST: postgres
  links:
    - redis
    - postgres
redis:
  image: redis
postgres:
  build: './docker/postgres'
  environment:
    POSTGRES_USER: docker
    POSTGRES_PASSWORD: docker

